### ISSUE TITLE
AMODE & RMODE 테스트

### ISSUE THREAD

**Issue by jangwon-han** [Tmaxsoft-Compiler/OFASM-test#12]
1. AMODE & RMODE test
- AMODE 테스트 방법: OFADBGREG 16를 사용하면 모든 레지스터 및 AMODE가 출력 된다
- RMODE 테스트 방법: OFADBGMEM SYM,2 명령어를 통해 프로그램내 특정 심볼을 출력해서 메모리 주소 공간을 확인한다. 참고로 RMODE 31 프로그램에 대해서는 0x01000000 이상의 메모리 영역에 할당되어 있어야 한다.

**Comment by joonho-jung** [comment]
동작확인하였습니다.
