### ISSUE TITLE
SAM24, SAM31, SAM64, BSM, BAKR 테스트

### ISSUE THREAD

**Issue by jangwon-han** [Tmaxsoft-Compiler/OFASM-test#13]
2. SAM24, SAM31, SAM64, BSM, BAKR 테스트
- 각각의 명령어에 대해서 AMODE가 제대로 변하고 있는지 확인한다.
- 단, 64비트 변환을 시도해도 31비트로 변환이 될 것이니 참고 바람.

**Comment by joonho-jung** [comment]
동작확인하였습니다.
