### ISSUE TITLE
CLOSE, GENCB

### ISSUE THREAD

**Issue by seokjun-hong** [Tmaxsoft-Compiler/OFASM-test#18]
@joonho-jung 

CLOSE, GENCB에서 누락된 데이터셋 파일들 풀리퀘스트 부탁드립니다~
gitignore를 해당 디렉토리에 추가하고 데이터셋 파일 커밋하시면됩니다!
불편드려 죄송합니다~

**Comment by joonho-jung** [comment]
동작확인하였습니다.
