### ISSUE TITLE
BXH instruction 이 두번 실행되는 문제

### ISSUE THREAD

**Issue by joonho-jung** [Tmaxsoft-Compiler/OFASM-test#20]
김혁 연구원님, BXH instruction 이 두번 실행되어 operand-1 의 값에 operand-3 이 두번 더해지는 문제가 있습니다. 관련 케이스와 로그를 첨부하였습니다.

< 14916  ==>  (BRZ01)BRZ01
< [00000001] 14916  ==>  LR      12,15
< [00000002] 14918  ==>  DBGREG  102
< OFASM: OFADBGREG[102], ADD WATCH REGISTER [2]
< OFASM: WATCHING REGISTER = R2
< [00000003] 14920  ==>  DBGREG  103
< OFASM: OFADBGREG[103], ADD WATCH REGISTER [3]
< OFASM: WATCHING REGISTER = R3
< [00000004] 14922  ==>  LA      2,12(0,12)
< [00000005] REG = [2]
< OLD=[0x0000000000000000]
< NEW=[0x0000000000003a50]
< 14926  ==>  BCR     15,2
< 14928  ==>  (BRZ01)START
< [00000006] 14928  ==>  L       2,96(0,12)
< [00000007] REG = [2]
< OLD=[0x0000000000003a50]
< NEW=[0x0000000000000002]
< 14932  ==>  C       2,88(0,12)
< [00000008] 14936  ==>  BRC     2,4
< 14944  ==>  (BRZ01)NEXT
< [00000009] 14944  ==>  DBGREG  2
32,61c2
< [00000010] 14946  ==>  L       2,100(0,12)
< [00000011] REG = [2]
< OLD=[0x0000000000000002]
< NEW=[0x0000000000000001]
< 14950  ==>  L       3,96(0,12)
< [00000012] REG = [3]
< OLD=[0x0000000000000000]
< NEW=[0x0000000000000002]
**< 14954  ==>  BXH     2,3,46(12)**
< [00000013] REG = [2]
< OLD=[0x0000000000000001]
< NEW=[0x0000000000000003]
**< 14954  ==>  BXH     2,3,46(12)**
< 14962  ==>  (BRZ01)NEXT2
< [00000014] REG = [2]
< OLD=[0x0000000000000003]
< NEW=[0x0000000000000005]

감사합니다.

[BRZ01.zip](https://github.com/Tmaxsoft-Compiler/OFASM-test/files/1477525/BRZ01.zip)

**Comment by ghost** [comment]
문제 해결했습니다.
문제는 기존에 잘 동작하던 BXH 명령어를 잘못 수정하여 발생했었습니다.
롤백하여 해결하였습니다.

김혁씨 이슈 닫아주세요.
